package main

const (
	envServerAutoprogrammingPromotionGuardianEnabledV0            = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_ENABLED"
	envServerAutoprogrammingPromotionGuardianCommandV0            = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_COMMAND"
	envServerAutoprogrammingPromotionGuardianRunnerEnvAllowlistV0 = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_RUNNER_ENV_ALLOWLIST"
	envServerAutoprogrammingPromotionGuardianStateDirV0           = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_STATE_DIR"
	envServerAutoprogrammingPromotionGuardianCurrentBinV0         = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_CURRENT_BIN"
	envServerAutoprogrammingPromotionGuardianCandidateBinV0       = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_CANDIDATE_BIN"
	envServerAutoprogrammingPromotionGuardianLastGoodBinV0        = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_LAST_GOOD_BIN"
	envServerAutoprogrammingPromotionGuardianArtifactRootV0       = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_ARTIFACT_ROOT"
	envServerAutoprogrammingPromotionGuardianTestCommandsV0       = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_TEST_COMMANDS"
	envServerAutoprogrammingPromotionGuardianBuildCommandV0       = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_BUILD_COMMAND"
	envServerAutoprogrammingPromotionGuardianHealthTimeoutMSV0    = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_HEALTH_TIMEOUT_MS"
	envServerAutoprogrammingPromotionGuardianCommandTimeoutMSV0   = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_COMMAND_TIMEOUT_MS"
	// Deprecated: use envServerAutoprogrammingPromotionGuardianHealthTimeoutMSV0.
	envServerAutoprogrammingPromotionGuardianHealthTimeoutV0 = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_HEALTH_TIMEOUT"
	// Deprecated: use envServerAutoprogrammingPromotionGuardianCommandTimeoutMSV0.
	envServerAutoprogrammingPromotionGuardianCommandTimeoutV0             = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_COMMAND_TIMEOUT"
	envServerAutoprogrammingPromotionGuardianArtifactMaxBytesV0           = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_ARTIFACT_MAX_BYTES"
	envServerAutoprogrammingPromotionGuardianRepairCommandV0              = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_COMMAND"
	envServerAutoprogrammingPromotionGuardianRepairCodexV0                = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX"
	envServerAutoprogrammingPromotionGuardianRepairCodexWriteSetV0        = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_WRITE_SET"
	envServerAutoprogrammingPromotionGuardianRepairCodexRequiredTestsV0   = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_REQUIRED_TESTS"
	envServerAutoprogrammingPromotionGuardianRepairCodexWorktreeRefV0     = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_WORKTREE_REF"
	envServerAutoprogrammingPromotionGuardianRepairCodexBranchRefV0       = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_BRANCH_REF"
	envServerAutoprogrammingPromotionGuardianRepairCodexRunRefV0          = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_RUN_REF"
	envServerAutoprogrammingPromotionGuardianRepairCodexPromotionRefV0    = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_PROMOTION_REF"
	envServerAutoprogrammingPromotionGuardianRepairCodexSandboxV0         = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_SANDBOX"
	envServerAutoprogrammingPromotionGuardianRepairCodexReasoningV0       = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_REASONING_EFFORT"
	envServerAutoprogrammingPromotionGuardianRepairCodexRuntimeDirV0      = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_RUNTIME_DIR"
	envServerAutoprogrammingPromotionGuardianRepairCodexAllowBroadV0      = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_ALLOW_BROAD_SANDBOX"
	envServerAutoprogrammingPromotionGuardianRepairCodexSandboxEvidenceV0 = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_REPAIR_CODEX_SANDBOX_EVIDENCE_REF"
	envServerAutoprogrammingPromotionGuardianCommandEffectEvidenceRefsV0  = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_COMMAND_EFFECT_EVIDENCE_REFS"
	envServerAutoprogrammingPromotionGuardianSkipHealthEvidenceRefsV0     = "ORQUESTA_SERVER_AUTOPROGRAMMING_PROMOTION_GUARDIAN_SKIP_HEALTH_EVIDENCE_REFS"
)

type serverAutoprogrammingPromotionGuardianDeprecatedEnvAliasV0 struct {
	LegacyKey    string
	CanonicalKey string
}

var serverAutoprogrammingPromotionGuardianDeprecatedEnvAliasesV0 = []serverAutoprogrammingPromotionGuardianDeprecatedEnvAliasV0{
	{
		LegacyKey:    envServerAutoprogrammingPromotionGuardianHealthTimeoutV0,
		CanonicalKey: envServerAutoprogrammingPromotionGuardianHealthTimeoutMSV0,
	},
	{
		LegacyKey:    envServerAutoprogrammingPromotionGuardianCommandTimeoutV0,
		CanonicalKey: envServerAutoprogrammingPromotionGuardianCommandTimeoutMSV0,
	},
}
