package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"go/token"
	"os"
	"strings"
)

type registryFile struct {
	SchemaVersion int           `json:"schema_version"`
	Revision      string        `json:"revision"`
	Keys          []registryKey `json:"keys"`
}

type registryKey struct {
	Key             string          `json:"key"`
	GoName          string          `json:"go_name"`
	Type            string          `json:"type"`
	Default         json.RawMessage `json:"default"`
	Sensitive       bool            `json:"sensitive"`
	Scope           string          `json:"scope"`
	RestartRequired bool            `json:"restart_required"`
	EnvAlias        string          `json:"env_alias"`
	AllowedValues   []string        `json:"allowed_values,omitempty"`
	Minimum         *int64          `json:"minimum,omitempty"`
	Maximum         *int64          `json:"maximum,omitempty"`
}

func main() {
	registryPath := flag.String("registry", "", "canonical registry path")
	outputPath := flag.String("output", "", "generated Go output path")
	flag.Parse()

	if strings.TrimSpace(*registryPath) == "" || strings.TrimSpace(*outputPath) == "" {
		fatalf("registry and output are required")
	}
	source, err := os.ReadFile(*registryPath)
	if err != nil {
		fatalf("read registry: %v", err)
	}

	var registry registryFile
	decoder := json.NewDecoder(bytes.NewReader(source))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&registry); err != nil {
		fatalf("decode registry: %v", err)
	}
	if err := validateRegistry(registry); err != nil {
		fatalf("validate registry: %v", err)
	}

	generated, err := render(registry, source)
	if err != nil {
		fatalf("render registry: %v", err)
	}
	if err := os.WriteFile(*outputPath, generated, 0o644); err != nil {
		fatalf("write generated keys: %v", err)
	}
}

func validateRegistry(registry registryFile) error {
	if registry.SchemaVersion < 1 {
		return fmt.Errorf("schema_version must be positive")
	}
	if strings.TrimSpace(registry.Revision) == "" {
		return fmt.Errorf("revision is required")
	}
	if len(registry.Keys) == 0 {
		return fmt.Errorf("keys are required")
	}

	keys := make(map[string]struct{}, len(registry.Keys))
	goNames := make(map[string]struct{}, len(registry.Keys))
	envAliases := make(map[string]struct{}, len(registry.Keys))
	for _, definition := range registry.Keys {
		if strings.TrimSpace(definition.Key) == "" {
			return fmt.Errorf("empty key")
		}
		if _, exists := keys[definition.Key]; exists {
			return fmt.Errorf("duplicate key %q", definition.Key)
		}
		keys[definition.Key] = struct{}{}

		if !token.IsIdentifier(definition.GoName) || !token.IsExported(definition.GoName) {
			return fmt.Errorf("invalid exported go_name %q", definition.GoName)
		}
		if _, exists := goNames[definition.GoName]; exists {
			return fmt.Errorf("duplicate go_name %q", definition.GoName)
		}
		goNames[definition.GoName] = struct{}{}

		if strings.TrimSpace(definition.EnvAlias) == "" {
			return fmt.Errorf("env_alias is required for %q", definition.Key)
		}
		if _, exists := envAliases[definition.EnvAlias]; exists {
			return fmt.Errorf("duplicate env_alias %q", definition.EnvAlias)
		}
		envAliases[definition.EnvAlias] = struct{}{}

		if definition.Type != "integer" && (definition.Minimum != nil || definition.Maximum != nil) {
			return fmt.Errorf("bounds require integer type for %q", definition.Key)
		}
		if definition.Minimum != nil && definition.Maximum != nil && *definition.Minimum > *definition.Maximum {
			return fmt.Errorf("minimum exceeds maximum for %q", definition.Key)
		}
	}
	return nil
}

func render(registry registryFile, source []byte) ([]byte, error) {
	digest := sha256.Sum256(source)
	var output bytes.Buffer
	output.WriteString("// Code generated by go generate; DO NOT EDIT.\n\n")
	output.WriteString("package config\n\n")
	fmt.Fprintf(&output, "const generatedRegistrySourceSHA256 = %q\n", hex.EncodeToString(digest[:]))
	fmt.Fprintf(&output, "const generatedRegistryRevision = %q\n\n", registry.Revision)
	output.WriteString("const (\n")
	for _, definition := range registry.Keys {
		fmt.Fprintf(&output, "\tKey%s Key = %q\n", definition.GoName, definition.Key)
	}
	output.WriteString(")\n\n")
	output.WriteString("func allGeneratedKeys() []Key {\n\treturn []Key{\n")
	for _, definition := range registry.Keys {
		fmt.Fprintf(&output, "\t\tKey%s,\n", definition.GoName)
	}
	output.WriteString("\t}\n}\n\n")
	output.WriteString("const generatedRegistryJSON = `")
	output.Write(source)
	if len(source) == 0 || source[len(source)-1] != '\n' {
		output.WriteByte('\n')
	}
	output.WriteString("`\n")

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, err
	}
	return formatted, nil
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
