package db

import (
	"strings"
	"testing"
)

func TestSchemaNoIncluyeCoordinacionPorFicherosObsoletos(t *testing.T) {
	t.Parallel()

	for _, prohibido := range []string{
		"Opinion.md",
		"Dudas.md",
		"ContaGrx/orquestacion.md",
		"en Opinion.md o en la BD",
		"PRAGMA journal_mode",
		"PRAGMA foreign_keys",
	} {
		if strings.Contains(Schema, prohibido) {
			t.Fatalf("Schema contiene referencia obsoleta: %q", prohibido)
		}
	}
}

func TestSchemaIncluyeCoordinacionMultiProyectoYMCP(t *testing.T) {
	t.Parallel()

	for _, requerido := range []string{
		"CREATE TABLE IF NOT EXISTS proyectos",
		"CREATE TABLE IF NOT EXISTS asignaciones",
		"CREATE TABLE IF NOT EXISTS conectores",
		"CREATE TABLE IF NOT EXISTS locks",
		"CREATE TABLE IF NOT EXISTS worktrees",
		"CREATE TABLE IF NOT EXISTS runtime_handles",
		"CREATE TABLE IF NOT EXISTS runtime_orders",
		"CREATE TABLE IF NOT EXISTS pools_capacidad",
		"CREATE TABLE IF NOT EXISTS pool_modelos",
		"CREATE TABLE IF NOT EXISTS politicas_modelo",
		"CREATE TABLE IF NOT EXISTS decisiones_proyecto",
		"CREATE TABLE IF NOT EXISTS documentos_externos",
		"CREATE TABLE IF NOT EXISTS git_merges",
		"external_session_id",
		"resumen_continuidad",
		"pool_id             INTEGER REFERENCES pools_capacidad(id)",
		"reasoning_effort TEXT NOT NULL DEFAULT ''",
	} {
		if !strings.Contains(Schema, requerido) {
			t.Fatalf("Schema no contiene el bloque esperado: %q", requerido)
		}
	}
}

func TestSchemaSeparadoEnDDLYSemillas(t *testing.T) {
	t.Parallel()

	ddl := schemaDDL()
	seeds := schemaSeedData()
	if ddl == "" {
		t.Fatalf("schema DDL vacio")
	}
	if seeds == "" {
		t.Fatalf("schema seeds vacio")
	}
	if strings.Contains(seeds, "INSERT OR IGNORE INTO agentes") {
		t.Fatalf("las semillas no deberian incluir agentes con INSERT OR IGNORE")
	}
	if strings.Contains(seeds, "INSERT OR IGNORE INTO config") {
		t.Fatalf("las semillas no deberian incluir config con INSERT OR IGNORE")
	}
	if strings.Contains(seeds, "INSERT OR IGNORE INTO reglas") {
		t.Fatalf("las semillas no deberian incluir reglas con INSERT OR IGNORE")
	}
	if strings.Contains(seeds, "INSERT OR IGNORE INTO skills") {
		t.Fatalf("las semillas no deberian incluir skills con INSERT OR IGNORE")
	}
	if strings.Contains(seeds, "INSERT OR IGNORE INTO workflows") {
		t.Fatalf("las semillas no deberian incluir workflows con INSERT OR IGNORE")
	}
	if strings.Contains(seeds, "INSERT OR IGNORE INTO") {
		t.Fatalf("las semillas no deberian usar INSERT OR IGNORE fijo")
	}
	if !strings.Contains(seeds, "INSERT INTO agentes") {
		t.Fatalf("las semillas deberian incluir agentes iniciales")
	}
	if !strings.Contains(seeds, "ON CONFLICT(nombre) DO NOTHING") {
		t.Fatalf("las semillas deberian usar conflicto por nombre para agentes")
	}
	if !strings.Contains(seeds, "INSERT INTO config") {
		t.Fatalf("las semillas deberian incluir config inicial")
	}
	if !strings.Contains(seeds, "ON CONFLICT(clave) DO NOTHING") {
		t.Fatalf("las semillas deberian usar conflicto por clave para config")
	}
	if !strings.Contains(seeds, "INSERT INTO reglas") {
		t.Fatalf("las semillas deberian incluir reglas iniciales")
	}
	if !strings.Contains(seeds, "ON CONFLICT(tipo_agente, titulo) DO NOTHING") {
		t.Fatalf("las semillas deberian usar conflicto compuesto para reglas")
	}
	if !strings.Contains(seeds, "INSERT INTO skills") {
		t.Fatalf("las semillas deberian incluir skills iniciales")
	}
	if !strings.Contains(seeds, "ON CONFLICT(tipo_agente, nombre) DO NOTHING") {
		t.Fatalf("las semillas deberian usar conflicto compuesto para skills")
	}
	if !strings.Contains(seeds, "INSERT INTO workflows") {
		t.Fatalf("las semillas deberian incluir workflows iniciales")
	}
	if !strings.Contains(seeds, "ON CONFLICT(nombre) DO NOTHING") {
		t.Fatalf("las semillas deberian usar conflicto por nombre para workflows")
	}
	if !strings.Contains(ddl, "CREATE TABLE IF NOT EXISTS reglas") {
		t.Fatalf("el DDL deberia incluir tablas de gobernanza")
	}
}

func TestSchemaSeedDataForDriverMySQLUsaInsertIgnore(t *testing.T) {
	t.Parallel()

	seeds := schemaSeedDataForDriver("mysql")
	if seeds == "" {
		t.Fatalf("schema seeds vacio para mysql")
	}
	if !strings.Contains(seeds, "INSERT IGNORE INTO agentes") {
		t.Fatalf("mysql deberia usar INSERT IGNORE para agentes")
	}
	if strings.Contains(seeds, "ON CONFLICT(") {
		t.Fatalf("mysql no deberia renderizar ON CONFLICT")
	}
}

func TestSchemaDDLForDriverPostgresReduceSintaxisSQLite(t *testing.T) {
	t.Parallel()

	for _, driver := range []string{"postgres", "postgresql"} {
		ddl := schemaDDLForDriver(driver)
		if ddl == "" {
			t.Fatalf("schema DDL vacio para %s", driver)
		}
		if strings.Contains(ddl, "AUTOINCREMENT") {
			t.Fatalf("%s no deberia conservar AUTOINCREMENT", driver)
		}
		if strings.Contains(ddl, "CREATE TRIGGER IF NOT EXISTS") {
			t.Fatalf("%s no deberia conservar triggers SQLite en este render minimo", driver)
		}
		if !strings.Contains(ddl, "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") {
			t.Fatalf("%s deberia usar columnas identity", driver)
		}
		if strings.Contains(ddl, " DATETIME") {
			t.Fatalf("%s no deberia conservar DATETIME", driver)
		}
		if !strings.Contains(ddl, " TIMESTAMP") {
			t.Fatalf("%s deberia convertir DATETIME a TIMESTAMP", driver)
		}
		if !strings.Contains(ddl, "CREATE TABLE IF NOT EXISTS proyectos") {
			t.Fatalf("%s deberia conservar las tablas base", driver)
		}
		if !strings.Contains(ddl, "CREATE OR REPLACE FUNCTION orquesta_set_updated_at()") {
			t.Fatalf("%s deberia declarar la funcion de updated_at", driver)
		}
		if count := strings.Count(ddl, "EXECUTE FUNCTION orquesta_set_updated_at()"); count != len(postgresUpdatedAtTables()) {
			t.Fatalf("%s deberia declarar %d triggers updated_at; obtuvo %d", driver, len(postgresUpdatedAtTables()), count)
		}
		if !strings.Contains(ddl, "BEFORE UPDATE ON tareas") {
			t.Fatalf("%s deberia recrear trigger updated_at para tareas", driver)
		}
		if strings.Contains(ddl, "UPDATE tareas SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;") {
			t.Fatalf("%s no deberia conservar el cuerpo de trigger SQLite", driver)
		}
	}
}

func TestBootstrapPlanForDriver(t *testing.T) {
	t.Parallel()

	for _, driver := range []string{"sqlite", "sqlite3", "postgres", "postgresql"} {
		plan, ok := bootstrapPlanForDriver(driver)
		if !ok {
			t.Fatalf("%s deberia tener bootstrap plan", driver)
		}
		if strings.TrimSpace(plan.DDL) == "" {
			t.Fatalf("%s deberia tener DDL", driver)
		}
		if strings.TrimSpace(plan.Seed) == "" {
			t.Fatalf("%s deberia tener semillas", driver)
		}
	}
	if _, ok := bootstrapPlanForDriver("mysql"); ok {
		t.Fatalf("mysql no deberia tener bootstrap plan todavia")
	}
}
