package db

import (
	"database/sql"
	"fmt"
	"strconv"
	"strings"
)

type schemaSectionRenderer struct {
	sqliteDDL string
	renderFor func(driver string) string
}

func schemaDDL() string {
	return schemaDDLForDriver(DriverName())
}

func schemaDDLForDriver(driver string) string {
	return joinDDLParts(schemaDDLPartsForDriver(driver)...)
}

func renderSQLiteBaseDDL() string {
	return renderBaseDDLForDriver("sqlite")
}

func renderPostgresBaseDDL() string {
	return renderBaseDDLForDriver("postgres")
}

func schemaDDLPartsForDriver(driver string) []string {
	return fallbackSchemaBackendSpec(driver).ddlParts()
}

func renderDriverColumnSyntax(driver, ddl string) string {
	switch normalizedDriverName(driver) {
	case "postgres":
		ddl = strings.ReplaceAll(ddl, "INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
		ddl = strings.ReplaceAll(ddl, " DATETIME", " TIMESTAMP")
	}
	return ddl
}

func renderBaseDDLForDriver(driver string) string {
	sections := schemaBaseSectionRenderers()
	rendered := make([]string, 0, len(sections))
	for _, section := range sections {
		if stmt := section.renderFor(driver); strings.TrimSpace(stmt) != "" {
			rendered = append(rendered, stmt)
		}
	}
	return joinDDLParts(rendered...)
}

func renderDriverSectionSyntax(driver, ddl string) string {
	statements := schemaStatements(ddl)
	out := make([]string, 0, len(statements))
	for _, stmt := range statements {
		out = append(out, renderDriverColumnSyntax(driver, stmt))
	}
	return strings.Join(out, "\n\n")
}

func schemaBaseSections() []string {
	renderers := schemaBaseSectionRenderers()
	sections := make([]string, 0, len(renderers))
	for _, section := range renderers {
		sections = append(sections, section.sqliteDDL)
	}
	return sections
}

func schemaBaseSectionRenderers() []schemaSectionRenderer {
	return []schemaSectionRenderer{
		{
			sqliteDDL: schemaBootstrapDDL,
			renderFor: renderBootstrapSectionDDLForDriver,
		},
		{
			sqliteDDL: schemaWorkflowDDL,
			renderFor: func(driver string) string { return renderDriverSectionSyntax(driver, schemaWorkflowDDL) },
		},
		{
			sqliteDDL: schemaCoordinationDDL,
			renderFor: func(driver string) string { return renderDriverSectionSyntax(driver, schemaCoordinationDDL) },
		},
		{
			sqliteDDL: schemaRuntimeDDL,
			renderFor: renderRuntimeSectionDDLForDriver,
		},
		{
			sqliteDDL: schemaCapacityDDL,
			renderFor: renderCapacitySectionDDLForDriver,
		},
		{
			sqliteDDL: schemaKnowledgeDDL,
			renderFor: func(driver string) string { return renderDriverSectionSyntax(driver, schemaKnowledgeDDL) },
		},
	}
}

func renderSQLiteAuxDDL() string {
	parts := []string{
		renderIndexDDL(),
		renderSQLiteUpdatedAtDDL(),
	}
	return joinDDLParts(parts...)
}

func renderPostgresAuxDDL() string {
	parts := []string{
		renderIndexDDL(),
		renderPostgresUpdatedAtDDL(),
	}
	return joinDDLParts(parts...)
}

func renderIndexDDL() string {
	return strings.Join(indexStatements(), "\n\n")
}

func renderSQLiteUpdatedAtDDL() string {
	var b strings.Builder
	for _, table := range updatedAtTables() {
		b.WriteString("CREATE TRIGGER IF NOT EXISTS trig_")
		b.WriteString(table)
		b.WriteString("_updated\n")
		b.WriteString("    AFTER UPDATE ON ")
		b.WriteString(table)
		b.WriteString("\n")
		b.WriteString("BEGIN\n")
		b.WriteString("    UPDATE ")
		b.WriteString(table)
		b.WriteString(" SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n")
		b.WriteString("END;\n\n")
	}
	return strings.TrimSpace(b.String())
}

func indexStatements() []string {
	return []string{
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_locks_scope_activo
ON locks(scope_type, scope_key)
WHERE estado = 'activa';`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_runtime_handles_agente_activo
ON runtime_handles(agente)
WHERE estado IN ('activo','pausado');`,
	}
}

func renderPostgresUpdatedAtDDL() string {
	var b strings.Builder
	b.WriteString(`CREATE OR REPLACE FUNCTION orquesta_set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
`)
	for _, table := range updatedAtTables() {
		triggerName := "trig_" + table + "_updated"
		b.WriteString("\nDO $$\nBEGIN\n")
		b.WriteString("    IF NOT EXISTS (\n")
		b.WriteString("        SELECT 1 FROM pg_trigger WHERE tgname = ")
		b.WriteString(strconv.Quote(triggerName))
		b.WriteString("\n    ) THEN\n")
		b.WriteString("        CREATE TRIGGER ")
		b.WriteString(triggerName)
		b.WriteString("\n")
		b.WriteString("        BEFORE UPDATE ON ")
		b.WriteString(table)
		b.WriteString("\n")
		b.WriteString("        FOR EACH ROW EXECUTE FUNCTION orquesta_set_updated_at();\n")
		b.WriteString("    END IF;\nEND $$;\n")
	}
	return strings.TrimSpace(b.String())
}

func updatedAtTables() []string {
	return []string{
		"tareas",
		"propuestas",
		"votos",
		"proyectos",
		"asignaciones",
		"conectores",
		"locks",
		"worktrees",
		"runtime_handles",
		"pools_capacidad",
		"pool_modelos",
		"politicas_modelo",
		"decisiones_proyecto",
		"documentos_externos",
		"git_merges",
	}
}

func joinDDLParts(parts ...string) string {
	var out []string
	for _, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		out = append(out, part)
	}
	return strings.Join(out, "\n\n")
}

func schemaStatements(schema string) []string {
	schema = strings.TrimSpace(schema)
	if schema == "" {
		return nil
	}
	var (
		statements []string
		current    strings.Builder
		inSingle   bool
		inDouble   bool
	)
	flush := func() {
		stmt := strings.TrimSpace(current.String())
		if stmt != "" {
			statements = append(statements, stmt)
		}
		current.Reset()
	}
	for i := 0; i < len(schema); i++ {
		ch := schema[i]
		switch ch {
		case '\'':
			if !inDouble {
				if inSingle && i+1 < len(schema) && schema[i+1] == '\'' {
					current.WriteByte(ch)
					current.WriteByte(schema[i+1])
					i++
					continue
				}
				inSingle = !inSingle
			}
		case '"':
			if !inSingle {
				inDouble = !inDouble
			}
		case ';':
			current.WriteByte(ch)
			if !inSingle && !inDouble {
				flush()
				continue
			}
		}
		current.WriteByte(ch)
	}
	flush()
	return statements
}

func aplicarDDL(db *sql.DB, ddl string) error {
	ddl = strings.TrimSpace(ddl)
	if ddl == "" {
		return fmt.Errorf("schema DDL vacio")
	}
	_, err := db.Exec(ddl)
	return err
}

func aplicarSeedSQL(db *sql.DB, seeds string) error {
	seeds = strings.TrimSpace(seeds)
	if seeds == "" {
		return nil
	}
	_, err := db.Exec(seeds)
	return err
}
