package db

import (
	"strings"
	"testing"
)

func TestRenderSchemaObjectsForDriverPostgresConvierteReviewGates(t *testing.T) {
	ddls := renderSchemaObjectsForDriver("postgres",
		"CREATE TABLE IF NOT EXISTS review_gates (",
		"CREATE INDEX IF NOT EXISTS idx_review_gates_proyecto_estado",
	)
	if len(ddls) != 2 {
		t.Fatalf("esperaba 2 sentencias, tengo %d", len(ddls))
	}
	if !strings.Contains(ddls[0], "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") {
		t.Fatalf("ddl review_gates no portable a postgres: %s", ddls[0])
	}
	if strings.Contains(ddls[0], "AUTOINCREMENT") || strings.Contains(ddls[0], " DATETIME") {
		t.Fatalf("ddl review_gates conserva sintaxis sqlite: %s", ddls[0])
	}
}

func TestRenderNotificacionesOutboxSchemaForDriverPostgresConvierteDDL(t *testing.T) {
	ddls := renderNotificacionesOutboxSchemaForDriver("postgres")
	if len(ddls) != 2 {
		t.Fatalf("esperaba 2 sentencias, tengo %d", len(ddls))
	}
	if !strings.Contains(ddls[0], "GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY") {
		t.Fatalf("ddl outbox no portable a postgres: %s", ddls[0])
	}
	if strings.Contains(ddls[0], "AUTOINCREMENT") || strings.Contains(ddls[0], " DATETIME") {
		t.Fatalf("ddl outbox conserva sintaxis sqlite: %s", ddls[0])
	}
}
