package db

import (
	"database/sql"
	"fmt"
	"strconv"
	"strings"
)

const (
	schemaUpdatedAtSectionStart = "-- ─── Triggers updated_at"
	schemaUpdatedAtSectionEnd   = "-- ─── Reglas por tipo de agente"
)

func schemaDDL() string {
	return schemaDDLForDriver(DriverName())
}

func schemaDDLForDriver(driver string) string {
	base := schemaWithoutUpdatedAtDDL(Schema)
	switch normalizedDriverName(driver) {
	case "postgres":
		return renderPostgresSchemaDDL(base)
	default:
		return renderSQLiteSchemaDDL(base)
	}
}

func renderSQLiteSchemaDDL(schema string) string {
	ddl := strings.TrimSpace(schema)
	if ddl == "" {
		return ""
	}
	return ddl + "\n\n" + renderSQLiteUpdatedAtDDL()
}

func renderPostgresSchemaDDL(schema string) string {
	lines := strings.Split(schema, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		line = strings.ReplaceAll(line, "INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
		line = strings.ReplaceAll(line, " DATETIME", " TIMESTAMP")
		out = append(out, line)
	}
	ddl := strings.TrimSpace(strings.Join(out, "\n"))
	if ddl == "" {
		return ""
	}
	return ddl + "\n\n" + renderPostgresUpdatedAtDDL()
}

func renderSQLiteUpdatedAtDDL() string {
	var b strings.Builder
	for _, table := range updatedAtTables() {
		b.WriteString("CREATE TRIGGER IF NOT EXISTS trig_")
		b.WriteString(table)
		b.WriteString("_updated\n")
		b.WriteString("    AFTER UPDATE ON ")
		b.WriteString(table)
		b.WriteString("\n")
		b.WriteString("BEGIN\n")
		b.WriteString("    UPDATE ")
		b.WriteString(table)
		b.WriteString(" SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;\n")
		b.WriteString("END;\n\n")
	}
	return strings.TrimSpace(b.String())
}

func renderPostgresUpdatedAtDDL() string {
	var b strings.Builder
	b.WriteString(`CREATE OR REPLACE FUNCTION orquesta_set_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
`)
	for _, table := range updatedAtTables() {
		triggerName := "trig_" + table + "_updated"
		b.WriteString("\nDO $$\nBEGIN\n")
		b.WriteString("    IF NOT EXISTS (\n")
		b.WriteString("        SELECT 1 FROM pg_trigger WHERE tgname = ")
		b.WriteString(strconv.Quote(triggerName))
		b.WriteString("\n    ) THEN\n")
		b.WriteString("        CREATE TRIGGER ")
		b.WriteString(triggerName)
		b.WriteString("\n")
		b.WriteString("        BEFORE UPDATE ON ")
		b.WriteString(table)
		b.WriteString("\n")
		b.WriteString("        FOR EACH ROW EXECUTE FUNCTION orquesta_set_updated_at();\n")
		b.WriteString("    END IF;\nEND $$;\n")
	}
	return strings.TrimSpace(b.String())
}

func updatedAtTables() []string {
	return []string{
		"tareas",
		"propuestas",
		"votos",
		"proyectos",
		"asignaciones",
		"conectores",
		"locks",
		"worktrees",
		"runtime_handles",
		"pools_capacidad",
		"pool_modelos",
		"politicas_modelo",
		"decisiones_proyecto",
		"documentos_externos",
		"git_merges",
	}
}

func schemaWithoutUpdatedAtDDL(schema string) string {
	schema = strings.TrimSpace(schema)
	if schema == "" {
		return ""
	}
	start := strings.Index(schema, schemaUpdatedAtSectionStart)
	end := strings.Index(schema, schemaUpdatedAtSectionEnd)
	if start == -1 || end == -1 || end <= start {
		return schema
	}
	before := strings.TrimRight(schema[:start], "\n")
	after := strings.TrimLeft(schema[end:], "\n")
	switch {
	case before == "":
		return after
	case after == "":
		return before
	default:
		return before + "\n\n" + after
	}
}

func aplicarDDL(db *sql.DB, ddl string) error {
	ddl = strings.TrimSpace(ddl)
	if ddl == "" {
		return fmt.Errorf("schema DDL vacio")
	}
	_, err := db.Exec(ddl)
	return err
}

func aplicarSeedSQL(db *sql.DB, seeds string) error {
	seeds = strings.TrimSpace(seeds)
	if seeds == "" {
		return nil
	}
	_, err := db.Exec(seeds)
	return err
}
