package db

import (
	"strings"
	"testing"
)

func TestRenderSupervisorSchemaObjectsForPostgresIsPortable(t *testing.T) {
	ddls := renderSupervisorSchemaObjectsForDriver("postgres",
		"CREATE TABLE IF NOT EXISTS supervisor_threads (",
		"CREATE TABLE IF NOT EXISTS supervisor_subagents (",
		"CREATE TABLE IF NOT EXISTS supervisor_pipeline_states (",
	)
	if len(ddls) == 0 {
		t.Fatal("se esperaba ddl supervisor renderizado para postgres")
	}
	for _, ddl := range ddls {
		if strings.Contains(ddl, "AUTOINCREMENT") {
			t.Fatalf("postgres no deberia conservar AUTOINCREMENT: %s", ddl)
		}
		if strings.Contains(ddl, " DATETIME") {
			t.Fatalf("postgres no deberia conservar DATETIME: %s", ddl)
		}
	}
	assertDDLContains(t, ddls, "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
	assertDDLContains(t, ddls, "first_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
	assertDDLContains(t, ddls, "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
	assertDDLContains(t, ddls, "started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP")
}

func assertDDLContains(t *testing.T, ddls []string, required string) {
	t.Helper()
	required = normalizeDDLWhitespace(required)
	for _, ddl := range ddls {
		if strings.Contains(normalizeDDLWhitespace(ddl), required) {
			return
		}
	}
	t.Fatalf("postgres deberia incluir %q en schema supervisor: %s", required, strings.Join(ddls, "\n"))
}

func normalizeDDLWhitespace(raw string) string {
	return strings.Join(strings.Fields(raw), " ")
}
