package orquestamcp

func mcpSharedContractSourcesV0() []mcpSharedContractSourceV0 {
	return []mcpSharedContractSourceV0{
		{
			Name:       "SolicitarNuevaApp",
			Slug:       "solicitar-nueva-app",
			Version:    "v0",
			Owner:      "orquesta-factory",
			MCPRole:    "tool_adapter",
			SummaryKey: "mcp.contracts.solicitar_nueva_app.summary.v0",
			CanonicalRefs: []string{
				"orquesta-factory/docs/contratos.md",
				"orquesta-factory/docs/schemas/app_spec_request_v0.schema.json",
				"orquesta-factory/docs/schemas/app_spec_v0.schema.json",
			},
			Input:  "AppSpecRequestV0",
			Output: "AppSpecV0 + BacklogInicialPropuestoV0",
			PublicErrors: []string{
				"app_spec_invalida",
				"opcion_incompatible",
				"target_no_soportado",
				"idioma_invalido",
				"conector_requerido_no_disponible",
			},
			Guardrails: []string{
				"no_persiste",
				"no_crea_tareas",
				"no_arranca_runtime",
				"validacion_delegada_en_factory",
			},
			ProgressKey:  "mcp.contracts.progress.descriptor_tool_puro_implementado.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
		{
			Name:       "PersistenceRepository",
			Slug:       "persistence-repository",
			Version:    "v0",
			Owner:      "orquesta-persistence",
			MCPRole:    "contract_reference",
			SummaryKey: "mcp.contracts.persistence_repository.summary.v0",
			CanonicalRefs: []string{
				"orquesta-persistence/docs/contratos.md",
				"orquesta-persistence/docs/schemas/persistence_repository_v0.schema.json",
			},
			Input:  "unidad de trabajo + payload versionado",
			Output: "estado persistido + proyecto_id opaco",
			PublicErrors: []string{
				"persistencia_no_disponible",
				"payload_invalido",
				"dialecto_no_soportado",
				"conflicto_idempotencia",
				"transaccion_fallida",
				"regla_negocio_en_adaptador",
			},
			Guardrails: []string{
				"db_es_adaptador",
				"sin_sql_driver_operativo",
				"idempotencia_obligatoria",
				"no_reglas_negocio_en_persistencia",
			},
			ProgressKey:  "mcp.contracts.progress.contrato_v0_compartido_adaptadores_opt_in.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
		{
			Name:       "RuntimeLaunchRequest",
			Slug:       "runtime-launch-request",
			Version:    "v0",
			Owner:      "orquesta-runtime",
			MCPRole:    "contract_reference",
			SummaryKey: "mcp.contracts.runtime_launch_request.summary.v0",
			CanonicalRefs: []string{
				"orquesta-runtime/docs/contratos.md",
				"orquesta-runtime/docs/schemas/runtime_launch_request_v0.schema.json",
			},
			Input:  "RuntimeLaunchRequestV0",
			Output: "RuntimeLaunchAcceptedV0 | RuntimeLaunchErrorV0",
			PublicErrors: []string{
				"runtime_launch_request_invalida",
				"function_contract_requerido",
				"function_contract_no_activa",
				"write_set_requerido",
				"write_set_invalido",
				"capacity_decision_requerida",
				"capacity_decision_no_soportada",
				"pool_ref_requerido",
				"model_ref_requerido",
				"home_ref_requerido",
				"credential_ref_requerido",
				"referencia_no_opaca",
				"secreto_detectado",
				"ruta_home_real_detectada",
				"mailbox_ref_requerido",
				"ack_ref_requerido",
				"readiness_ref_requerido",
				"idempotency_key_requerida",
				"runtime_no_disponible",
			},
			Guardrails: []string{
				"runtime_ejecuta_no_decide",
				"solo_referencias_opacas",
				"sin_secretos_rutas_home_prompts_transcripts",
				"errores_por_message_key_i18n",
			},
			ProgressKey:  "mcp.contracts.progress.contrato_v0_validado_runtime_opt_in.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
		{
			Name:       "OrquestaEvent",
			Slug:       "orquesta-event",
			Version:    "v0",
			Owner:      "orquesta-observability",
			MCPRole:    "compact_projection_future",
			SummaryKey: "mcp.contracts.orquesta_event.summary.v0",
			CanonicalRefs: []string{
				"orquesta-observability/docs/contratos.md",
				"orquesta-observability/docs/schemas/orquesta_event_v0.schema.json",
			},
			Input:  "PublishOrquestaEventRequestV0",
			Output: "PublishOrquestaEventAcceptedV0",
			PublicErrors: []string{
				"orquesta_event_invalido",
				"evento_demasiado_extenso",
				"secreto_detectado",
				"transcript_no_permitido",
				"correlation_id_requerido",
				"idempotency_key_requerida",
				"source_area_no_soportada",
				"event_type_incompatible",
				"sink_no_disponible",
				"duplicado_idempotente",
			},
			Guardrails: []string{
				"observability_no_decide",
				"eventos_compactos",
				"sin_sink_operativo_transcripts",
				"mcp_lee_proyecciones_no_sink",
			},
			ProgressKey:  "mcp.contracts.progress.proyecciones_compactas_por_puerto.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
		{
			Name:       "GovernanceCatalog",
			Slug:       "governance-catalog",
			Version:    "v0",
			Owner:      "orquesta-governance",
			MCPRole:    "compact_read_resource",
			SummaryKey: "mcp.contracts.governance_catalog.summary.v0",
			CanonicalRefs: []string{
				"orquesta-governance/docs/contratos.md",
				"orquesta-governance/docs/schemas/governance_catalog_v0.schema.json",
			},
			Input:  "consulta compacta por modulo, rol o fase",
			Output: "GovernanceCatalogV0",
			PublicErrors: []string{
				"governance_catalog_source_unavailable",
				"governance_catalog_invalid_source",
				"governance_catalog_entry_without_origin",
				"governance_catalog_entry_without_promotion_criteria",
				"governance_catalog_forbidden_activation",
				"governance_catalog_secret_detected",
				"governance_catalog_text_only_secret_control",
				"governance_entry_effective_without_decision",
				"governance_entry_text_only_secret_control",
			},
			Guardrails: []string{
				"dbv1_evidencia_no_canon",
				"effective_requiere_decision",
				"controles_secretos_estructurados",
				"governance_no_ejecuta",
			},
			ProgressKey:  "mcp.contracts.progress.consulta_compacta_read_only_vigente.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
		{
			Name:       "OperationalStatusQuery",
			Slug:       "operational-status-query",
			Version:    "v0",
			Owner:      "orquesta-observability",
			MCPRole:    "compact_read_resource",
			SummaryKey: "mcp.contracts.operational_status_query.summary.v0",
			CanonicalRefs: []string{
				"orquesta-observability/docs/contratos.md",
			},
			Input:  "OperationalStatusQueryV0",
			Output: "DiagnosticoCompactoV0",
			PublicErrors: []string{
				"operational_status_query_invalida",
				"consumidor_no_autorizado",
				"scope_no_soportado",
				"referencia_no_opaca",
				"consulta_demasiado_amplia",
				"proyeccion_no_disponible",
				"diagnostico_no_disponible",
				"frescura_no_garantizada",
				"secreto_detectado",
				"transcript_no_permitido",
			},
			Guardrails: []string{
				"read_only",
				"sin_db_runtime_sink_directo",
				"referencias_opacas",
				"recuperacion_activa_fuera_de_contrato",
			},
			ProgressKey:  "mcp.contracts.progress.resource_operational_status_vigente.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
		{
			Name:       "DeploymentPlan",
			Slug:       "deployment-plan",
			Version:    "v0",
			Owner:      "orquesta-deploy",
			MCPRole:    "contract_reference",
			SummaryKey: "mcp.contracts.deployment_plan.summary.v0",
			CanonicalRefs: []string{
				"orquesta-deploy/docs/contratos.md",
			},
			Input:  "request de plan con app_spec_id y deploy_target",
			Output: "plan declarativo de deploy",
			PublicErrors: []string{
				"deploy_target_requerido",
				"deploy_target_no_soportado",
				"matriz_os_incompleta",
				"contenedor_no_aceptado",
				"validacion_entorno_incompleta",
				"healthcheck_incompleto",
				"rollback_incompleto",
				"artefactos_previstos_incompletos",
				"secreto_detectado",
				"proveedor_hardcodeado",
				"script_sin_contrato",
			},
			Guardrails: []string{
				"plan_declarativo_no_ejecutable",
				"sin_iac_scripts_pipelines",
				"sin_secretos_home_db_runtime_modelo",
				"adaptador_real_requiere_smoke",
			},
			ProgressKey:  "mcp.contracts.progress.schema_harness_deploy_vigente.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
		{
			Name:       "GenerarI18nDocsIniciales",
			Slug:       "generar-i18n-docs-iniciales",
			Version:    "v0",
			Owner:      "orquesta-i18n-docs",
			MCPRole:    "contract_reference",
			SummaryKey: "mcp.contracts.generar_i18n_docs_iniciales.summary.v0",
			CanonicalRefs: []string{
				"orquesta-i18n-docs/docs/contratos.md",
				"orquesta-i18n-docs/docs/schemas/app_i18n_docs_plan_v0.schema.json",
				"orquesta-i18n-docs/docs/schemas/i18n_bundle_v0.schema.json",
				"orquesta-i18n-docs/docs/schemas/docs_bundle_v0.schema.json",
			},
			Input:  "AppSpecV0 validada + locales + salidas solicitadas",
			Output: "AppI18nDocsPlanV0",
			PublicErrors: []string{
				"app_spec_requerida",
				"app_spec_no_validada",
				"idioma_ui_requerido",
				"idioma_docs_requerido",
				"idioma_invalido",
				"default_locale_fuera_de_catalogo",
				"salida_requerida_incompatible",
				"plantilla_no_disponible",
				"locale_sin_catalogo",
				"clave_requerida_faltante",
				"clave_inestable",
				"estructura_bundle_incompatible",
				"documento_sin_idioma",
				"tipo_documento_faltante",
				"contenido_sin_clave_i18n",
			},
			Guardrails: []string{
				"textos_visibles_por_catalogos",
				"documento_declara_locale",
				"plan_serializable_no_filesystem",
				"sin_llm_persistencia_apps_tareas_backlog",
			},
			ProgressKey:  "mcp.contracts.progress.builder_harness_relacional_vigente.v0",
			BacklogRefs:  mcpBacklogT25RefsV0(),
			Verification: mcpMCPResourceVerificationV0(),
		},
	}
}
