package orquestadomainwork

import "testing"

func TestExpectedDomainWorkArtifactTypeForWorkKindV0(t *testing.T) {
	cases := map[string]string{
		"draft_content_block":             DomainWorkArtifactTypeContentBlockV0,
		"generate_block":                  DomainWorkArtifactTypeContentBlockV0,
		"generate_program_topic_draft":    DomainWorkArtifactTypeContentBlockV0,
		"generate_visual_asset":           DomainWorkArtifactTypeVisualAssetV0,
		"review_legal":                    DomainWorkArtifactTypeBlockRevisionV0,
		"review_pedagogical":              DomainWorkArtifactTypeBlockRevisionV0,
		"review_quality":                  DomainWorkArtifactTypeBlockRevisionV0,
		"validate_topic":                  DomainWorkArtifactTypeBlockRevisionV0,
		"research_sources":                DomainWorkArtifactTypeSourceV0,
		"download_source":                 DomainWorkArtifactTypeSourceV0,
		"verify_sources":                  DomainWorkArtifactTypeSourceV0,
		"research_exam_precedents":        DomainWorkArtifactTypeExamResearchReportV0,
		"research_exam_results":           DomainWorkArtifactTypeExamResearchReportV0,
		"buscar_examenes_ope":             DomainWorkArtifactTypeExamResearchReportV0,
		"split_syllabus_topic":            DomainWorkArtifactTypeTopicStructureV0,
		"draft_topic_outline":             DomainWorkArtifactTypeTopicOutlineV0,
		"create_exam_outline":             DomainWorkArtifactTypeTopicOutlineV0,
		"summarize_block":                 DomainWorkArtifactTypeTopicSummaryV0,
		"summarize_chapter":               DomainWorkArtifactTypeTopicSummaryV0,
		"summarize_topic":                 DomainWorkArtifactTypeTopicSummaryV0,
		"expand_topic_from_summary":       DomainWorkArtifactTypeTopicExpansionPackageV0,
		"plan_documento":                  DomainDocumentPlanArtifactTypeV0,
		"plan_tema":                       DomainDocumentPlanArtifactTypeV0,
		"plan_temario":                    DomainDocumentPlanArtifactTypeV0,
		"assemble_topic":                  DomainWorkArtifactTypeAssembledTopicV0,
		"generate_question_bank":          DomainWorkArtifactTypeQuestionBankV0,
		"generate_topic_tests":            DomainWorkArtifactTypeQuestionBankV0,
		"generate_html_site":              DomainWorkArtifactTypeLocalHTMLSiteV0,
		"assemble_local_html_site":        DomainWorkArtifactTypeLocalHTMLSiteV0,
		"generate_audio_asset":            DomainWorkArtifactTypeAudioAssetV0,
		"generate_topic_audio":            DomainWorkArtifactTypeAudioAssetV0,
		"audio_tema":                      DomainWorkArtifactTypeAudioAssetV0,
		"generacion_audio":                DomainWorkArtifactTypeAudioAssetV0,
		"tts_topic":                       DomainWorkArtifactTypeAudioAssetV0,
		"generate_tutor_assets":           DomainWorkArtifactTypeTutorBotPackageV0,
		"configure_temario_bots":          DomainWorkArtifactTypeTutorBotPackageV0,
		"generate_rag_assets":             DomainWorkArtifactTypeTutorBotPackageV0,
		"generate_interactive_practice":   DomainWorkArtifactTypeInteractivePracticeV0,
		"create_interactive_practice":     DomainWorkArtifactTypeInteractivePracticeV0,
		"generate_practice_package":       DomainWorkArtifactTypeInteractivePracticeV0,
		"generate_learning_games":         DomainWorkArtifactTypeInteractivePracticeV0,
		"generate_help_package":           DomainWorkArtifactTypeHelpPackageV0,
		"create_help_package":             DomainWorkArtifactTypeHelpPackageV0,
		"generate_help_manual_assets":     DomainWorkArtifactTypeHelpPackageV0,
		"review_agent_independent":        DomainWorkArtifactTypeAgentReviewReportV0,
		"review_codex":                    DomainWorkArtifactTypeAgentReviewReportV0,
		"review_gemini":                   DomainWorkArtifactTypeAgentReviewReportV0,
		"review_claude":                   DomainWorkArtifactTypeAgentReviewReportV0,
		"review_agent_pair":               DomainWorkArtifactTypeAgentPairReviewReportV0,
		"review_pair_codex_gemini":        DomainWorkArtifactTypeAgentPairReviewReportV0,
		"review_pair_codex_claude":        DomainWorkArtifactTypeAgentPairReviewReportV0,
		"review_pair_gemini_claude":       DomainWorkArtifactTypeAgentPairReviewReportV0,
		"generate_agent_candidate":        DomainWorkArtifactTypeAgentCandidateV0,
		"vote_agent_candidates":           DomainWorkArtifactTypeAgentCandidateVoteV0,
		"select_agent_candidate_director": DomainWorkArtifactTypeAgentCandidateSelectV0,
		"review_director_consolidation":   DomainWorkArtifactTypeDirectorReviewMatrixV0,
		"finalize_domain_package":         DomainWorkArtifactTypeFinalDomainPackageV0,
		"finalize_topic_package":          DomainWorkArtifactTypeFinalDomainPackageV0,
		"finalize_temario_package":        DomainWorkArtifactTypeFinalDomainPackageV0,
		"unknown_work_kind":               DomainWorkArtifactTypeGenericWorkDeliveryV0,
	}
	for workKind, want := range cases {
		if got := ExpectedDomainWorkArtifactTypeForWorkKindV0(workKind); got != want {
			t.Fatalf("%s artifact=%s want=%s", workKind, got, want)
		}
	}
}
