package orquestaopesbridge

func opesGlobalEditorialPolicyV0() []string {
	return []string{
		"guia_global_estilo_2026_05_18_aplica_a_todos_los_temarios_opes",
		"objetivo: tema profesional, estudiable, riguroso, trazable y preparado para examen; no volcado de informacion",
		"A1: 45-50 folios, 20.250-22.500 palabras, minimo de cierre 20.250 palabras salvo regla superior explicita",
		"minimos de cierre por nivel sobre ampliado publicable: A1 20.250 palabras, A2 14.400, B 10.800, C1 7.200, C2 4.500 y AP 3.150; el resumen no sustituye al ampliado",
		"no marcar ready_profesional, ready_candidate_html ni apto_para_subida_controlada si cualquier tema no alcanza el minimo aplicable",
		"todo cierre textual o de curso debe generar informe_extension_temario.json y .md con conteo por tema, folios equivalentes, deficit y estado",
		"estructura minima: orientacion examen, mapa/ruta, conceptos clave, definiciones autoridad, bloques cortos, tablas, ejemplos, modo tutor, notas test, visuales, supuestos, errores, repaso, enfoque, muestra test y fuentes",
		"flujo temario completo local: investigacion de examenes relacionados, redaccion por temas, infografias por tema, banco de tests, revisiones, validacion, ensamblado, audios por apartado, tutor/bots, HTML local operativo y manuales graficos de ayuda USO antes de produccion",
		"investigacion externa: buscar por internet examenes, convocatorias, temarios y pruebas de administraciones relacionadas; priorizar boletines, sedes oficiales, tribunales, universidades/institutos publicos y fuentes sindicales verificables; registrar URL, fecha, administracion, anio, categoria y utilidad",
		"temas comunes: antes de redactar o generar derivados, inventariar comunes ya creados por grupo/nivel y reutilizar contenido, tests, visuales, audios y manifests compatibles; no reinventar temas comunes existentes salvo justificacion expresa de obsolescencia, error grave o falta real de encaje",
		"si un comun existente no encaja de forma exacta, conservarlo como insumo y crear derivacion localizada por nivel/cuerpo; no tirar ni rehacer desde cero por diferencias de titulo, alias, orden o metadatos reparables",
		"modo tutor completo: que significa, por que importa, con que se confunde y como se reconoce en examen",
		"tono adulto, claro y tecnico; facil pedagogicamente, no infantilizar ni rellenar",
		"si existe tema o artefacto previo, estudiar primero que falla y priorizar modificacion localizada; rehacer completo solo con justificacion cuando sea mas sencillo o seguro que corregir",
		"notas de test separadas de la teoria; distractores y trampas solo en notas de test, enfoque o repaso",
		"primera lectura continua; tablas, esquemas, test y visuales son apoyo y no sustituyen el desarrollo teorico",
		"comprension lectora: una idea por parrafo, tecnicismo explicado, definicion antes del desarrollo complejo y ejemplos despues de conceptos abstractos",
		"metodo asimilacion: recuperacion activa, repaso espaciado, ejemplos trabajados, carga cognitiva controlada, doble codificacion, elaboracion e intercalado",
		"test progresivo en niveles base, aplicacion y examen real solo como banco privado para afiliados; no publicar test de prueba dentro del tema abierto",
		"banco_preguntas_i18n_es.json obligatorio para afiliados: minimo 50 preguntas por tema, 4 respuestas A/B/C/D por pregunta, una correcta exacta y distractores plausibles que exijan conocer bien la materia; debe quedar en el mismo paquete/directorio de su temario; prohibido banco comun, banco global o reutilizacion indiferenciada entre temas; prohibidos distractores tontos, absurdos, mecanicos, de descarte por longitud o claramente descartables",
		"tests OPES: no modificar bancos originales sin orden expresa; crear salida nueva por banco/test_id, JSON por tema, HTML revisable por tema, index.html, metadata.json, informe Markdown y SQL local solo si procede; validar estructura y dificultad/proximidad antes de dar listo; las coincidencias literales reparables se corrigen sin tirar bancos aprovechables",
		"tests TCAE: en temas comunes no mencionar TCAE si el contenido debe valer para cualquier OPE; en temas especificos usar TCAE como nombre principal y no Auxiliar de Enfermeria",
		"revision independiente obligatoria: Codex, Gemini y Claude deben revisar curso, temas, tests, visuales, audios, tutor, HTML, manuales y paquete antes del cierre, con informes separados",
		"revision por pares obligatoria: Codex-Gemini, Codex-Claude y Gemini-Claude deben contrastar acuerdos, discrepancias, riesgos y rework causal; en tests publicables se revisa el 100% de preguntas/opciones por lotes si hace falta",
		"candidatos alternativos: si tests, tutor, visuales, explicaciones o bloques concretos son flojos, Orquesta puede pedir candidatos a Codex, Gemini y Claude; se conservan todos y los tres votan antes de que el Director seleccione o fusione",
		"consolidacion del Director obligatoria: el Director integra revisiones independientes y por pares, acepta artefactos, pide rework localizado, conserva material recuperable y bloquea solo por causa real",
		"tutor diagnostico de test: concepto fallado, por que la opcion elegida es incorrecta y donde repasar",
		"tutor/bots del temario obligatorios para local: responder dudas por tema/apartado, explicar fallos de test, recomendar repaso y limitarse a fuentes y contenido del paquete",
		"audios accesibles obligatorios: audio por tema y por apartado/seccion, manifest con segments por section_ref, duracion, formato, checksum/ref, reutilizacion previa de audios comunes compatibles y revision de numeros romanos antes de TTS",
		"HTML local obligatorio antes de produccion: usar logos USO, capa protegida #uso-material-watermark y el formato real de curso de la web USO/TCAE promocion interna que aporte el adaptador OPES/USO; estructura html_final, audio/manifests, locales/i18n, navegacion, modo estudio, audios, tutor, tests permitidos y assets locales deben funcionar sin backend productivo",
		"manuales graficos de ayuda USO obligatorios cuando haya HTML local revisable: seguir SCREENSHOT_HELP_MANUALS.md, YAML -> capturas -> index.html -> manual.pdf -> manual.md, con regla de marca USO, comentarios fuera de capturas y revision visual",
		"cierre 100%: no marcar ready, ready_profesional, ready_candidate_html ni apto_para_subida_controlada sin completed_syllabus_package con resumido, ampliado, fuentes, tests, visuales finales, audios, tutor, HTML, manuales, manifest, validacion visual y matriz de revisiones cerrada",
		"cierre OPES final: el receipt debe aportar evidencia opes-extension-minima-passed y opes-common-canonical-reuse-passed u opes-common-master-not-applicable",
		"supuestos practicos guiados cuando proceda: situacion, pistas, preguntas, resolucion paso a paso, errores, criterio y mini comprobacion",
		"repaso antes del examen: mapa de 5-7 ideas, definiciones rapidas, diferencias, errores, checklist y preguntas de recuperacion",
		"visuales utiles no decorativos; preferir SVG, HTML o CSS determinista para diagramas con rotulos; fotos solo oficiales, licenciadas o generadas cuando aporten aprendizaje",
		"movil: esquemas responsivos con scroll horizontal; no recortar contenido ni hacerlo ilegible",
		"fuentes: normativa oficial espanola y europea primero; BOE, BOJA, BOP y UE; doctrina, jurisprudencia y guias; internacionales solo como apoyo",
		"texto visible no muestra rutas, agentes, prompts, arquitectura, ids tecnicos ni decisiones internas",
		"contenido visible de interfaz debe ser i18n/localizable en todos los cursos; el contenido doctrinal puede quedar en castellano salvo orden de traduccion, pero controles, labels, mensajes, tests y feedback deben usar claves/locales",
		"prohibido: listas densas sin explicar, parrafos con demasiadas comas, tono infantil, visuales decorativos, bancos completos dentro del tema, distractores absurdos y marcadores editoriales visibles sin resolver",
	}
}

func opesTemarioAgentRulesV0() []string {
	return []string{
		"canon_externo=/home/alberto/Trabajo/OPES/AGENTS.md",
		"leer_antes_de_temarios=ENTRADA_UNICA_SIGUIENTE_AGENTE_OPES.md|GUIA_ESTILO_TEMARIOS_OPES_GLOBAL_2026-05-18.md|USO_ORQUESTA_TEMARIOS_OPES_GUIA_AGENTES_2026-06-04.md",
		"actuar_como_director_editorial: revisar mapa, dependencias, canones, estado y fuentes antes de redactar",
		"no_rehacer_por_defecto: inventariar temas, comunes, tests, audios, visuales, HTML, tutor/RAG, manifests y paquetes; reutilizar o adaptar lo valido",
		"alcance_busqueda: empezar por course_id/topic_id/programa/canon/materiales reutilizables y excluir por defecto backups, paquetes historicos, snapshots, runtime, orquesta_state, runtime_orquesta, bin y ficheros de control salvo auditoria global explicita",
		"alcance_recuperable: hallazgos fuera de alcance se conservan como evidencia blanda o nota de revision; no bloquean ni descartan trabajo util por si solos",
		"minimos_extension: informe_extension_temario.json/.md obligatorio; ampliado minimo A1 20250, A2 14400, B 10800, C1 7200, C2 4500, AP 3150 palabras",
		"comunes_maestro: todo comun deriva de maestro A1/A1-A2 o superior validado; si no aplica, declararlo explicitamente",
		"paralelismo_temario: un agente padre por tema independiente y hasta seis subagentes por padre salvo limite duro externo documentado",
		"visuales: Gemini o rol visual equivalente para foto/imagen realista cuando aporte aprendizaje; infografia profesional para conceptos abstractos; no aceptar maquetas como arte final",
		"validacion_visual: capturas de todos los HTML publicables, escritorio y movil cuando haya tablas, visuales, formularios o bloques densos",
		"audios_bloqueantes: no marcar ready si faltan audio/manifests o MP3 por tema/apartado cuando el curso los requiere",
		"tests: bancos publicables revisados al 100% por Codex, Gemini y Claude por lotes si hace falta",
		"candidatos: cuando una pieza concreta no de nivel, Codex/Gemini/Claude pueden crear candidatos alternativos; despues los tres votan y el Director decide ganador, fusion o rework",
		"triple_visto_bueno: Codex, Gemini y Claude revisan curso antes de candidato listo; el Director consolida y pide rework sin tirar material recuperable",
		"revision_pares: Codex-Gemini, Codex-Claude y Gemini-Claude contrastan sus revisiones antes de que el Director cierre",
		"cierre_100: entregar completed_syllabus_package con manifest, validacion y matriz de revisiones antes de produccion",
		"web_publicable: i18n completo y arquitectura hexagonal; subir temarios por API, no copiando carpetas ni tocando BD a mano",
	}
}
