#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Smoke real BUG-165/065: coordina por /api/v0/autoprogramming/status y
# /api/v0/server/shutdown {"cleanup_goal_backends":true}; no usa run-control.
export ORQUESTA_GOAL_FIRST_SMOKE_HIGH_CONSUMPTION_MODE=1
export SMOKE_GOAL_FIRST_SHUTDOWN_COORDINATION_MODE=1
export ORQUESTA_CODEX_GOAL_BACKEND="${ORQUESTA_CODEX_GOAL_BACKEND:-app_server_tmux}"
export ORQUESTA_CODEX_GOAL_TIMEOUT_MS="${ORQUESTA_CODEX_GOAL_TIMEOUT_MS:-600000}"
export ORQUESTA_CODEX_SANDBOX="${ORQUESTA_CODEX_SANDBOX:-danger-full-access}"
export ORQUESTA_CODEX_APPROVAL_POLICY="${ORQUESTA_CODEX_APPROVAL_POLICY:-never}"
export ORQUESTA_SERVER_GOAL_OBSERVER_ENABLED="${ORQUESTA_SERVER_GOAL_OBSERVER_ENABLED:-true}"
export ORQUESTA_SERVER_GOAL_OBSERVER_INTERVAL_MS="${ORQUESTA_SERVER_GOAL_OBSERVER_INTERVAL_MS:-1000}"
export ORQUESTA_SERVER_GOAL_OBSERVER_MAX_ITEMS="${ORQUESTA_SERVER_GOAL_OBSERVER_MAX_ITEMS:-5}"
export ORQUESTA_SERVER_GOAL_OBSERVER_FINGERPRINT_ENABLED="${ORQUESTA_SERVER_GOAL_OBSERVER_FINGERPRINT_ENABLED:-false}"
export ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_HIGH_CONSUMPTION_TOKENS="${ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_HIGH_CONSUMPTION_TOKENS:-1}"
export ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_MAX_WAIT_SECONDS="${ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_MAX_WAIT_SECONDS:-1}"
export ORQUESTA_AUTOPROGRAMMING_NO_CHECKPOINT_WARNING_MAX_WAIT_SECONDS="${ORQUESTA_AUTOPROGRAMMING_NO_CHECKPOINT_WARNING_MAX_WAIT_SECONDS:-1}"
export ORQUESTA_GOAL_FIRST_SHUTDOWN_COORDINATION_POLLS="${ORQUESTA_GOAL_FIRST_SHUTDOWN_COORDINATION_POLLS:-12}"
export ORQUESTA_GOAL_FIRST_SHUTDOWN_COORDINATION_SLEEP_SECONDS="${ORQUESTA_GOAL_FIRST_SHUTDOWN_COORDINATION_SLEEP_SECONDS:-1}"

# El script delegado debe terminar con app_server_tmux_processes_alive=0 y
# smoke_goal_first_shutdown_coordination_real=ok si el contrato se cumple.
exec "$repo_root/scripts/smoke_goal_first_app_server_real.sh" "$@"
