#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export ORQUESTA_GOAL_FIRST_SMOKE_HIGH_CONSUMPTION_MODE=1
export ORQUESTA_CODEX_GOAL_BACKEND="${ORQUESTA_CODEX_GOAL_BACKEND:-app_server_tmux}"
export ORQUESTA_CODEX_GOAL_TIMEOUT_MS="${ORQUESTA_CODEX_GOAL_TIMEOUT_MS:-600000}"
export ORQUESTA_CODEX_SANDBOX="${ORQUESTA_CODEX_SANDBOX:-danger-full-access}"
export ORQUESTA_CODEX_APPROVAL_POLICY="${ORQUESTA_CODEX_APPROVAL_POLICY:-never}"
export ORQUESTA_SERVER_GOAL_OBSERVER_ENABLED="${ORQUESTA_SERVER_GOAL_OBSERVER_ENABLED:-true}"
export ORQUESTA_SERVER_GOAL_OBSERVER_INTERVAL_MS="${ORQUESTA_SERVER_GOAL_OBSERVER_INTERVAL_MS:-1000}"
export ORQUESTA_SERVER_GOAL_OBSERVER_MAX_ITEMS="${ORQUESTA_SERVER_GOAL_OBSERVER_MAX_ITEMS:-5}"
export ORQUESTA_SERVER_GOAL_OBSERVER_FINGERPRINT_ENABLED="${ORQUESTA_SERVER_GOAL_OBSERVER_FINGERPRINT_ENABLED:-false}"
export ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_HIGH_CONSUMPTION_TOKENS="${ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_HIGH_CONSUMPTION_TOKENS:-1}"
export ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_MAX_WAIT_SECONDS="${ORQUESTA_AUTOPROGRAMMING_CHECKPOINT_ONLY_MAX_WAIT_SECONDS:-1}"
export ORQUESTA_AUTOPROGRAMMING_NO_CHECKPOINT_WARNING_MAX_WAIT_SECONDS="${ORQUESTA_AUTOPROGRAMMING_NO_CHECKPOINT_WARNING_MAX_WAIT_SECONDS:-1}"

exec "$repo_root/scripts/smoke_goal_first_app_server_real.sh" "$@"
